# Generated by Django 4.1.7 on 2023-03-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CreateModel',
        ),
    ]
