# Generated by Django 4.1.7 on 2023-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_createmodel_generate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='generate_type',
            field=models.TextField(choices=[('1', '項目作成'), ('2', 'リンク項目作成')], default=('2', 'リンク項目作成'), verbose_name='項目タイプ'),
        ),
    ]
