# Generated by Django 4.1.7 on 2023-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_alter_createmodel_generate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmodel',
            name='column_type',
            field=models.TextField(choices=[('1', '項目作成'), ('2', 'リンク項目作成')], default=('1', '項目作成'), verbose_name='項目タイプ'),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='generate_type',
            field=models.TextField(choices=[('1', '組み合わせ'), ('2', 'ランダム')], default=('1', '組み合わせ'), verbose_name='生成タイプ'),
        ),
    ]
