# Generated by Django 4.1.7 on 2023-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0005_createmodel_column_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmodel',
            name='link_column_name',
            field=models.CharField(default='AAA', max_length=50),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='column_name',
            field=models.CharField(default='AAA', max_length=50),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='column_type',
            field=models.TextField(choices=[('1', '文字'), ('2', '数値'), ('3', '日付'), ('4', '日時')], default=('3', '日付'), verbose_name='データタイプ'),
        ),
    ]
