# Generated by Django 4.1.7 on 2023-03-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_createmodel_link_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmodel',
            name='data_type',
            field=models.TextField(choices=[('1', '文字'), ('2', '数値'), ('3', '日付'), ('4', '日時')], default=('3', '日付'), verbose_name='データタイプ'),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='column_type',
            field=models.TextField(choices=[('1', '項目作成'), ('2', 'リンク項目作成')], default=('1', '項目作成'), verbose_name='項目タイプ'),
        ),
    ]
