# Generated by Django 4.1.7 on 2023-03-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0010_alter_createmodel_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='column_type',
            field=models.CharField(choices=[('1', '項目作成'), ('2', 'リンク項目作成')], default='1', max_length=20, verbose_name='項目タイプ'),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='data_type',
            field=models.CharField(choices=[('1', '文字'), ('2', '数値'), ('3', '日付'), ('4', '日時')], default='3', max_length=20, verbose_name='データタイプ'),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='generate_type',
            field=models.CharField(choices=[('1', '組み合わせ'), ('2', 'ランダム')], default='1', max_length=20, verbose_name='生成タイプ'),
        ),
    ]
