# Generated by Django 4.1.7 on 2023-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0011_alter_createmodel_column_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='column_name',
            field=models.CharField(max_length=50),
        ),
    ]
