# Generated by Django 4.1.7 on 2023-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0012_alter_createmodel_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='column_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='data_type',
            field=models.CharField(choices=[('1', '文字'), ('2', '数値'), ('3', '日付'), ('4', '日時')], max_length=20, verbose_name='データタイプ'),
        ),
        migrations.AlterField(
            model_name='createmodel',
            name='generate_type',
            field=models.CharField(max_length=20),
        ),
    ]
