# Generated by Django 4.1.7 on 2023-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0014_createdataconfigmodel_createlinkdataconfigmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdataconfigmodel',
            name='date_step',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createdataconfigmodel',
            name='datetime_step',
            field=models.IntegerField(),
        ),
    ]
