# Generated by Django 4.1.7 on 2023-03-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0016_newcreatemodel_delete_createdataconfigmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCreateModel',
            new_name='CreateModel',
        ),
    ]
