# Generated by Django 4.1.7 on 2023-02-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_product_and_random', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
