# Generated by Django 4.1.7 on 2023-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_product_and_random', '0002_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
