# Generated by Django 4.1.7 on 2023-02-20 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_product_and_random', '0004_alter_post_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='json file', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
