# Generated by Django 4.1.7 on 2023-03-07 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_product_and_random', '0005_post_title_alter_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(upload_to='uploads/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
